<div class="module callToActionsModule <?= $this->expandFirst() ? 'callToActionsModule--expandFirst' : ''; ?> <?= $this->getBackgroundClass(); ?>" <?= $this->hasBackgroundImage() ? 'style="background-image: url(\''. $this->getBackgroundImage().'\');"' : ''?>>
	<div class="callToActionsModule-wrapper">
		<?php
			foreach( $this->getBlocks() as $block) {
				$block->printHTML();
			}
		?>
		<div style="clear:both"></div>
	</div>
</div>