<div class="module headerModule">
	<div class="headerModule-spacer"></div>
	<div class="headerModule-foreground headerModule-layer">
		<div class="table-height"></div>
		<div class="headerModule-foreground-content">
			<?php if( $this->getHeading() != null && $this->getHeading() != ""): ?>
			<h1 class="headerModule-heading"><?= $this->getHeading(); ?></h1>
			<?php endif; ?>
			<?php if( $this->getSubHeading() != null && $this->getSubHeading() != ""): ?>
			<div class="headerModule-subheading"><?= $this->getSubHeading(); ?></div>
			<?php endif; ?>
		</div>
	</div>
		<?php
			$background_template = $this->directory() . '/' . 'header-background--'.$this->getBackgroundType() . '.phtml';
			if( file_exists($background_template)) {
				include $background_template;
			}
		?>
</div>